sudo: false
language: node_js
node_js:
  - '10'
services:
- docker
branches:
  only:
    - master
before_install:
  - npm i
script:
  - npm start
  - docker build -t egg-ci .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 18410408685/egg-ci:latest
